services:
  samba:
    image: dperson/samba
    container_name: samba
    restart: always
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - /mnt/hd_alan:/mnt/hd_alan
    environment:
      - USERID=1000
      - GROUPID=1000
      - SAMBA_USER=alan
      - SAMBA_PASSWORD=Al@n2107
      - TZ=America/Sao_Paulo
    command: '-u "alan;Al@n2107" -s "hd_alan;/mnt/hd_alan;yes;no;no;all;none"'
