server:
  http_listen_port: 9080
  grpc_listen_port: 9095

positions:
  filename: /var/log/promtail-positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: log4j
    static_configs:
      - targets:
          - localhost
        labels:
          job: log4j
          __path__: /var/log/log4j/*.log

