services:
  stirlingpdf:
    image: frooodle/s-pdf:0.29.0-ultra-lite
    container_name: stirlingpdf
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=America/Sao_Paulo
    restart: unless-stopped

